"""xnano._core

Type stubs for the ``rust`` ported primitives derived from the ``ratatui`` and ``tachyonfx``
creates.
"""

from __future__ import annotations

from collections.abc import Callable, Sequence
from enum import IntEnum
from typing import Any, Optional, Tuple, Type, overload

class Rect:
    """Axis-aligned rectangle.

    Maps to :class:`ratatui::layout::Rect`.
    See https://docs.rs/ratatui/0.29.0/ratatui/layout/struct.Rect.html
    """

    def __init__(
        self, x: int = 0, y: int = 0, width: int = 0, height: int = 0
    ) -> None: ...
    @staticmethod
    def zero() -> Rect: ...
    @property
    def x(self) -> int: ...
    @property
    def y(self) -> int: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    def area(self) -> int: ...
    def is_empty(self) -> bool: ...
    def inner(self, margin: Margin) -> Rect: ...
    def left(self) -> int: ...
    def right(self) -> int: ...
    def top(self) -> int: ...
    def bottom(self) -> int: ...
    def offset(self, offset: Offset) -> Rect: ...
    def union(self, other: Rect) -> Rect: ...
    def intersection(self, other: Rect) -> Rect: ...
    def intersects(self, other: Rect) -> bool: ...
    def contains(self, x: int, y: int) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class Margin:
    """Layout margin.

    Maps to :class:`ratatui::layout::Margin`.
    See https://docs.rs/ratatui/0.29.0/ratatui/layout/struct.Margin.html
    """

    def __init__(self, horizontal: int = 0, vertical: int = 0) -> None: ...
    @property
    def horizontal(self) -> int: ...
    @property
    def vertical(self) -> int: ...
    def __repr__(self) -> str: ...

class Direction(IntEnum):
    """Layout direction.

    Maps to :class:`ratatui::layout::Direction`.
    See https://docs.rs/ratatui/0.29.0/ratatui/layout/enum.Direction.html
    """

    Horizontal = ...
    Vertical = ...

class Alignment(IntEnum):
    """Text alignment.

    Maps to :class:`ratatui::layout::Alignment`.
    See https://docs.rs/ratatui/0.29.0/ratatui/layout/enum.Alignment.html
    """

    Left = ...
    Center = ...
    Right = ...

class Flex(IntEnum):
    """Flex distribution mode for layout constraints.

    Maps to :class:`ratatui::layout::Flex`.
    See https://docs.rs/ratatui/0.29.0/ratatui/layout/enum.Flex.html
    """

    Legacy = ...
    Start = ...
    End = ...
    Center = ...
    SpaceBetween = ...
    SpaceAround = ...

class Constraint:
    """Layout size constraint.

    Maps to :class:`ratatui::layout::Constraint`.
    See https://docs.rs/ratatui/0.29.0/ratatui/layout/enum.Constraint.html
    """

    @staticmethod
    def min(value: int) -> Constraint: ...
    @staticmethod
    def max(value: int) -> Constraint: ...
    @staticmethod
    def length(value: int) -> Constraint: ...
    @staticmethod
    def percentage(value: int) -> Constraint: ...
    @staticmethod
    def ratio(numerator: int, denominator: int) -> Constraint: ...
    @staticmethod
    def fill(value: int) -> Constraint: ...
    @staticmethod
    def from_lengths(values: Sequence[int]) -> list[Constraint]: ...
    @staticmethod
    def from_percentages(values: Sequence[int]) -> list[Constraint]: ...
    @staticmethod
    def from_ratios(values: Sequence[Tuple[int, int]]) -> list[Constraint]: ...
    @staticmethod
    def from_mins(values: Sequence[int]) -> list[Constraint]: ...
    @staticmethod
    def from_maxes(values: Sequence[int]) -> list[Constraint]: ...
    @staticmethod
    def from_fills(values: Sequence[int]) -> list[Constraint]: ...
    def apply(self, length: int) -> int: ...
    def __repr__(self) -> str: ...

class Offset:
    """Signed offset.

    Maps to :class:`ratatui::layout::Offset`.
    See https://docs.rs/ratatui/0.29.0/ratatui/layout/struct.Offset.html
    """

    def __init__(self, x: int = 0, y: int = 0) -> None: ...
    @property
    def x(self) -> int: ...
    @property
    def y(self) -> int: ...

class Size:
    """Terminal size.

    Maps to :class:`ratatui::layout::Size`.
    See https://docs.rs/ratatui/0.29.0/ratatui/layout/struct.Size.html
    """

    def __init__(self, width: int, height: int) -> None: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    def __repr__(self) -> str: ...

class Layout:
    """Constraint-based layout splitter.

    Maps to :class:`ratatui::layout::Layout`.
    See https://docs.rs/ratatui/0.29.0/ratatui/layout/struct.Layout.html
    """

    @staticmethod
    def default() -> Layout: ...
    @staticmethod
    def new(
        direction: Direction, constraints: Sequence[Constraint]
    ) -> Layout: ...
    @staticmethod
    def vertical(constraints: Sequence[Constraint]) -> Layout: ...
    @staticmethod
    def horizontal(constraints: Sequence[Constraint]) -> Layout: ...
    def direction(self, direction: Direction) -> Layout: ...
    def constraints(self, constraints: Sequence[Constraint]) -> Layout: ...
    def margin(self, value: int) -> Layout: ...
    def margin_xy(self, margin: Margin) -> Layout: ...
    def horizontal_margin(self, value: int) -> Layout: ...
    def vertical_margin(self, value: int) -> Layout: ...
    def flex(self, flex: Flex) -> Layout: ...
    def spacing(self, value: int) -> Layout: ...
    def split(self, area: Rect) -> list[Rect]: ...
    def __repr__(self) -> str: ...

class Color:
    """Terminal color.

    Maps to :class:`ratatui::style::Color`.
    See https://docs.rs/ratatui/0.29.0/ratatui/style/enum.Color.html
    """

    RESET: Color
    BLACK: Color
    RED: Color
    GREEN: Color
    YELLOW: Color
    BLUE: Color
    MAGENTA: Color
    CYAN: Color
    GRAY: Color
    DARK_GRAY: Color
    LIGHT_RED: Color
    LIGHT_GREEN: Color
    LIGHT_YELLOW: Color
    LIGHT_BLUE: Color
    LIGHT_MAGENTA: Color
    LIGHT_CYAN: Color
    WHITE: Color

    @staticmethod
    def parse(value: str) -> Color: ...
    @staticmethod
    def indexed(value: int) -> Color: ...
    @staticmethod
    def rgb(r: int, g: int, b: int) -> Color: ...
    @staticmethod
    def from_u32(value: int) -> Color: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Modifier:
    """Text style modifier flags.

    Maps to :class:`ratatui::style::Modifier`.
    See https://docs.rs/ratatui/0.29.0/ratatui/style/struct.Modifier.html
    """

    BOLD: Modifier
    DIM: Modifier
    ITALIC: Modifier
    UNDERLINED: Modifier
    SLOW_BLINK: Modifier
    RAPID_BLINK: Modifier
    REVERSED: Modifier
    HIDDEN: Modifier
    CROSSED_OUT: Modifier
    EMPTY: Modifier

    def __or__(self, other: Modifier) -> Modifier: ...
    def __repr__(self) -> str: ...

class Style:
    """Combined foreground, background, and modifier style.

    Maps to :class:`ratatui::style::Style`.
    See https://docs.rs/ratatui/0.29.0/ratatui/style/struct.Style.html
    """

    @staticmethod
    def default() -> Style: ...
    @staticmethod
    def new() -> Style: ...
    @staticmethod
    def reset() -> Style: ...
    def fg(self, color: Color) -> Style: ...
    def bg(self, color: Color) -> Style: ...
    def add_modifier(self, modifier: Modifier) -> Style: ...
    def remove_modifier(self, modifier: Modifier) -> Style: ...
    def patch(self, other: Style) -> Style: ...
    def __repr__(self) -> str: ...

def color_from_hsl(h: float, s: float, l: float) -> Color:
    """Create a color from HSL components.

    Uses the ``palette`` crate; see also
    https://docs.rs/ratatui/0.29.0/ratatui/style/enum.Color.html#method.from_hsl
    """

def color_from_hex(value: str) -> Color:
    """Parse a hex color string (``#RGB`` or ``#RRGGBB``)."""

def color_lerp(a: Color, b: Color, t: float) -> Color:
    """Linearly interpolate between two colors."""

def tailwind_color(name: str, shade: int) -> Color:
    """Look up a Tailwind CSS palette color.

    Maps to :class:`ratatui::style::palette::tailwind`.
    See https://docs.rs/ratatui/0.29.0/ratatui/style/palette/tailwind/index.html
    """

class Span:
    """Styled text span.

    Maps to :class:`ratatui::text::Span`.
    See https://docs.rs/ratatui/0.29.0/ratatui/text/struct.Span.html
    """

    @staticmethod
    def default() -> Span: ...
    @staticmethod
    def raw(content: str) -> Span: ...
    @staticmethod
    def styled(content: str, style: Style) -> Span: ...
    def content(self, value: str) -> Span: ...
    def style(self, style: Style) -> Span: ...
    def patch_style(self, style: Style) -> Span: ...
    def reset_style(self) -> Span: ...
    def width(self) -> int: ...
    @property
    def text(self) -> str: ...
    def __repr__(self) -> str: ...

class Line:
    """A line of styled spans.

    Maps to :class:`ratatui::text::Line`.
    See https://docs.rs/ratatui/0.29.0/ratatui/text/struct.Line.html
    """

    @staticmethod
    def raw(content: str) -> Line: ...
    @staticmethod
    def styled(content: str, style: Style) -> Line: ...
    @staticmethod
    def from_spans(spans: Sequence[Span]) -> Line: ...
    def style(self, style: Style) -> Line: ...
    def patch_style(self, style: Style) -> Line: ...
    def reset_style(self) -> Line: ...
    def width(self) -> int: ...
    def alignment(self, alignment: Alignment) -> Line: ...
    def left_aligned(self) -> Line: ...
    def centered(self) -> Line: ...
    def right_aligned(self) -> Line: ...
    def spans(self, spans: Sequence[Span]) -> Line: ...
    def __repr__(self) -> str: ...

class Text:
    """Multi-line styled text.

    Maps to :class:`ratatui::text::Text`.
    See https://docs.rs/ratatui/0.29.0/ratatui/text/struct.Text.html
    """

    @staticmethod
    def raw(content: str) -> Text: ...
    @staticmethod
    def styled(content: str, style: Style) -> Text: ...
    @staticmethod
    def from_lines(lines: Sequence[Line]) -> Text: ...
    def style(self, style: Style) -> Text: ...
    def patch_style(self, style: Style) -> Text: ...
    def reset_style(self) -> Text: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def alignment(self, alignment: Alignment) -> Text: ...
    def left_aligned(self) -> Text: ...
    def centered(self) -> Text: ...
    def right_aligned(self) -> Text: ...
    def __repr__(self) -> str: ...

def styled_span(
    content: str,
    fg: Optional[Color] = None,
    bg: Optional[Color] = None,
    modifiers: Optional[Modifier] = None,
) -> Span:
    """Convenience helper to build a :class:`Span` from style shorthand."""

class Borders:
    """Border flag set.

    Maps to :class:`ratatui::widgets::Borders`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/struct.Borders.html
    """

    NONE: Borders
    TOP: Borders
    RIGHT: Borders
    BOTTOM: Borders
    LEFT: Borders
    ALL: Borders

    def __or__(self, other: Borders) -> Borders: ...
    def __repr__(self) -> str: ...

class BorderType(IntEnum):
    """Border rendering style.

    Maps to :class:`ratatui::widgets::BorderType`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/enum.BorderType.html
    """

    Plain = ...
    Rounded = ...
    Double = ...
    Thick = ...
    QuadrantInside = ...
    QuadrantOutside = ...

class TitlePosition(IntEnum):
    """Block title position.

    Maps to :class:`ratatui::widgets::block::Position`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/block/enum.Position.html
    """

    Top = ...
    Bottom = ...

class HighlightSpacing(IntEnum):
    """Highlight spacing for list/table widgets.

    Maps to :class:`ratatui::widgets::HighlightSpacing`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/enum.HighlightSpacing.html
    """

    Always = ...
    WhenSelected = ...
    Never = ...

class Wrap:
    """Paragraph word-wrap settings.

    Maps to :class:`ratatui::widgets::Wrap`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/struct.Wrap.html
    """

    def __init__(self, trim: bool = False) -> None: ...

class Block:
    """Decorative block with optional borders and title.

    Maps to :class:`ratatui::widgets::Block`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/struct.Block.html
    """

    @staticmethod
    def new() -> Block: ...
    @staticmethod
    def default() -> Block: ...
    @staticmethod
    def bordered() -> Block: ...
    def borders(self, borders: Borders) -> Block: ...
    def border_style(self, style: Style) -> Block: ...
    def border_type(self, border_type: BorderType) -> Block: ...
    def style(self, style: Style) -> Block: ...
    def title(self, title: Any) -> Block: ...
    def title_alignment(self, alignment: Alignment) -> Block: ...
    def title_style(self, style: Style) -> Block: ...
    def title_top(self, title: Any) -> Block: ...
    def title_bottom(self, title: Any) -> Block: ...
    def title_position(self, position: TitlePosition) -> Block: ...
    def title_at(self, title: Any, position: TitlePosition) -> Block: ...
    def inner(self, area: Rect) -> Rect: ...
    def padding(self, padding: Padding) -> Block: ...
    def __repr__(self) -> str: ...

class Paragraph:
    """Multi-line text widget.

    Maps to :class:`ratatui::widgets::Paragraph`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/struct.Paragraph.html
    """

    @staticmethod
    def new(content: Any) -> Paragraph: ...
    def block(self, block: Block) -> Paragraph: ...
    def style(self, style: Style) -> Paragraph: ...
    def wrap(self, wrap: Wrap) -> Paragraph: ...
    def alignment(self, alignment: Alignment) -> Paragraph: ...
    def left_aligned(self) -> Paragraph: ...
    def centered(self) -> Paragraph: ...
    def right_aligned(self) -> Paragraph: ...
    def scroll(self, x: int, y: int) -> Paragraph: ...
    def __repr__(self) -> str: ...

class ListItem:
    """Single list entry.

    Maps to :class:`ratatui::widgets::ListItem`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/struct.ListItem.html
    """

    @staticmethod
    def new(content: Any) -> ListItem: ...
    def style(self, style: Style) -> ListItem: ...
    def __repr__(self) -> str: ...

class ListDirection(IntEnum):
    """List rendering direction.

    Maps to :class:`ratatui::widgets::ListDirection`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/enum.ListDirection.html
    """

    TopToBottom = ...
    BottomToTop = ...

class RatList:
    """Selectable list widget.

    Python name ``RatList`` maps to :class:`ratatui::widgets::List`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/struct.List.html
    """

    @staticmethod
    def new(items: Sequence[Any]) -> RatList: ...
    def block(self, block: Block) -> RatList: ...
    def style(self, style: Style) -> RatList: ...
    def highlight_style(self, style: Style) -> RatList: ...
    def direction(self, direction: ListDirection) -> RatList: ...
    def highlight_symbol(self, symbol: str) -> RatList: ...
    def items(self, items: Sequence[Any]) -> RatList: ...
    def repeat_highlight_symbol(self, repeat: bool) -> RatList: ...
    def highlight_spacing(self, spacing: HighlightSpacing) -> RatList: ...
    def scroll_padding(self, padding: int) -> RatList: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def __repr__(self) -> str: ...

class ListState:
    """Mutable state for :class:`RatList`.

    Maps to :class:`ratatui::widgets::ListState`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/struct.ListState.html
    """

    def __init__(self) -> None: ...
    def select(self, index: Optional[int] = None) -> None: ...
    @property
    def selected(self) -> Optional[int]: ...
    def select_next(self) -> None: ...
    def select_previous(self) -> None: ...
    def select_first(self) -> None: ...
    def select_last(self) -> None: ...
    @property
    def offset(self) -> int: ...
    def set_offset(self, value: int) -> None: ...
    def scroll_down_by(self, amount: int) -> None: ...
    def scroll_up_by(self, amount: int) -> None: ...
    def __repr__(self) -> str: ...

class Gauge:
    """Progress gauge widget.

    Maps to :class:`ratatui::widgets::Gauge`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/struct.Gauge.html
    """

    @staticmethod
    def new() -> Gauge: ...
    @staticmethod
    def default() -> Gauge: ...
    def block(self, block: Block) -> Gauge: ...
    def style(self, style: Style) -> Gauge: ...
    def gauge_style(self, style: Style) -> Gauge: ...
    def percent(self, value: int) -> Gauge: ...
    def ratio(self, value: float) -> Gauge: ...
    def label(self, label: Any) -> Gauge: ...
    def use_unicode(self, value: bool) -> Gauge: ...
    def __repr__(self) -> str: ...

class Clear:
    """Widget that clears the render area.

    Maps to :class:`ratatui::widgets::Clear`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/struct.Clear.html
    """

    @staticmethod
    def new() -> Clear: ...

class Padding:
    """Block inner padding.

    Maps to :class:`ratatui::widgets::block::Padding`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/block/struct.Padding.html
    """

    @staticmethod
    def zero() -> Padding: ...
    @staticmethod
    def uniform(value: int) -> Padding: ...
    @staticmethod
    def horizontal(value: int) -> Padding: ...
    @staticmethod
    def vertical(value: int) -> Padding: ...
    @staticmethod
    def symmetric(horizontal: int, vertical: int) -> Padding: ...
    @staticmethod
    def new(left: int, right: int, top: int, bottom: int) -> Padding: ...

class Position:
    """Cursor position.

    Maps to :class:`ratatui::layout::Position`.
    See https://docs.rs/ratatui/0.29.0/ratatui/layout/struct.Position.html
    """

    ORIGIN: Position

    def __init__(self, x: int, y: int) -> None: ...
    @property
    def x(self) -> int: ...
    @property
    def y(self) -> int: ...

class Cell:
    """Table cell.

    Maps to :class:`ratatui::widgets::Cell`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/struct.Cell.html
    """

    @staticmethod
    def new(content: Any) -> Cell: ...
    def style(self, style: Style) -> Cell: ...
    def content(self, value: Any) -> Cell: ...

class Row:
    """Table row.

    Maps to :class:`ratatui::widgets::Row`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/struct.Row.html
    """

    @staticmethod
    def new(cells: Sequence[Any]) -> Row: ...
    def style(self, style: Style) -> Row: ...
    def height(self, value: int) -> Row: ...
    def top_margin(self, value: int) -> Row: ...
    def bottom_margin(self, value: int) -> Row: ...
    def cells(self, cells: Sequence[Any]) -> Row: ...

class RatTable:
    """Table widget.

    Python name ``RatTable`` maps to :class:`ratatui::widgets::Table`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/struct.Table.html
    """

    @staticmethod
    def new(rows: Sequence[Row], widths: Sequence[Constraint]) -> RatTable: ...
    def header(self, row: Row) -> RatTable: ...
    def footer(self, row: Row) -> RatTable: ...
    def block(self, block: Block) -> RatTable: ...
    def style(self, style: Style) -> RatTable: ...
    def row_highlight_style(self, style: Style) -> RatTable: ...
    def column_highlight_style(self, style: Style) -> RatTable: ...
    def cell_highlight_style(self, style: Style) -> RatTable: ...
    def highlight_symbol(self, symbol: Any) -> RatTable: ...
    def highlight_spacing(self, spacing: HighlightSpacing) -> RatTable: ...
    def rows(self, rows: Sequence[Row]) -> RatTable: ...
    def widths(self, widths: Sequence[Constraint]) -> RatTable: ...
    def column_spacing(self, value: int) -> RatTable: ...

class TableState:
    """Mutable state for :class:`RatTable`.

    Maps to :class:`ratatui::widgets::TableState`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/struct.TableState.html
    """

    def __init__(self) -> None: ...
    def select(self, index: Optional[int] = None) -> None: ...
    @property
    def selected(self) -> Optional[int]: ...
    @property
    def selected_column(self) -> Optional[int]: ...
    def selected_cell(self) -> Optional[Tuple[int, int]]: ...
    @property
    def offset(self) -> int: ...
    def select_column(self, index: Optional[int] = None) -> None: ...
    def select_cell(
        self, indexes: Optional[Tuple[int, int]] = None
    ) -> None: ...
    def select_next(self) -> None: ...
    def select_previous(self) -> None: ...
    def select_next_column(self) -> None: ...
    def select_previous_column(self) -> None: ...
    def select_first(self) -> None: ...
    def select_last(self) -> None: ...
    def select_first_column(self) -> None: ...
    def select_last_column(self) -> None: ...
    def scroll_down_by(self, amount: int) -> None: ...
    def scroll_up_by(self, amount: int) -> None: ...
    def scroll_right_by(self, amount: int) -> None: ...
    def scroll_left_by(self, amount: int) -> None: ...

class ScrollbarOrientation(IntEnum):
    """Scrollbar orientation.

    Maps to :class:`ratatui::widgets::ScrollbarOrientation`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/enum.ScrollbarOrientation.html
    """

    VerticalRight = ...
    VerticalLeft = ...
    HorizontalBottom = ...
    HorizontalTop = ...

class Scrollbar:
    """Scrollbar widget.

    Maps to :class:`ratatui::widgets::Scrollbar`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/struct.Scrollbar.html
    """

    @staticmethod
    def new(orientation: ScrollbarOrientation) -> Scrollbar: ...
    def style(self, style: Style) -> Scrollbar: ...
    def thumb_style(self, style: Style) -> Scrollbar: ...
    def track_style(self, style: Style) -> Scrollbar: ...
    def begin_style(self, style: Style) -> Scrollbar: ...
    def end_style(self, style: Style) -> Scrollbar: ...
    def begin_symbol(self, symbol: Optional[str] = None) -> Scrollbar: ...
    def end_symbol(self, symbol: Optional[str] = None) -> Scrollbar: ...

class ScrollDirection(IntEnum):
    """Scrollbar scroll direction.

    Maps to :class:`ratatui::widgets::ScrollDirection`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/enum.ScrollDirection.html
    """

    Forward = ...
    Backward = ...

class ScrollbarState:
    """Mutable state for :class:`Scrollbar`.

    Maps to :class:`ratatui::widgets::ScrollbarState`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/struct.ScrollbarState.html
    """

    def __init__(self, content_length: int) -> None: ...
    def set_position(self, value: int) -> None: ...
    def set_content_length(self, value: int) -> None: ...
    def viewport_content_length(self, value: int) -> ScrollbarState: ...
    def prev(self) -> None: ...
    def next(self) -> None: ...
    def first(self) -> None: ...
    def last(self) -> None: ...
    def scroll(self, direction: ScrollDirection) -> None: ...

class Tabs:
    """Tab bar widget.

    Maps to :class:`ratatui::widgets::Tabs`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/struct.Tabs.html
    """

    @staticmethod
    def new(titles: Sequence[Any]) -> Tabs: ...
    def block(self, block: Block) -> Tabs: ...
    def style(self, style: Style) -> Tabs: ...
    def highlight_style(self, style: Style) -> Tabs: ...
    def titles(self, titles: Sequence[Any]) -> Tabs: ...
    def select(self, index: Optional[int] = None) -> Tabs: ...
    def padding(self, left: str, right: str) -> Tabs: ...
    def padding_left(self, value: str) -> Tabs: ...
    def padding_right(self, value: str) -> Tabs: ...
    def divider(self, symbol: str) -> Tabs: ...

class Sparkline:
    """Sparkline chart widget.

    Maps to :class:`ratatui::widgets::Sparkline`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/struct.Sparkline.html
    """

    @staticmethod
    def default() -> Sparkline: ...
    @staticmethod
    def new(data: Sequence[int]) -> Sparkline: ...
    def data(self, data: Sequence[int]) -> Sparkline: ...
    def block(self, block: Block) -> Sparkline: ...
    def style(self, style: Style) -> Sparkline: ...
    def max(self, value: int) -> Sparkline: ...
    def absent_value_style(self, style: Style) -> Sparkline: ...
    def absent_value_symbol(self, symbol: str) -> Sparkline: ...

class LineGauge:
    """Horizontal line gauge widget.

    Maps to :class:`ratatui::widgets::LineGauge`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/struct.LineGauge.html
    """

    @staticmethod
    def new() -> LineGauge: ...
    def ratio(self, value: float) -> LineGauge: ...
    def label(self, label: Any) -> LineGauge: ...
    def block(self, block: Block) -> LineGauge: ...
    def style(self, style: Style) -> LineGauge: ...
    def filled_style(self, style: Style) -> LineGauge: ...
    def unfilled_style(self, style: Style) -> LineGauge: ...

class Bar:
    """Single bar in a bar chart.

    Maps to :class:`ratatui::widgets::Bar`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/struct.Bar.html
    """

    @staticmethod
    def default() -> Bar: ...
    @staticmethod
    def new(value: int, label: str) -> Bar: ...
    def value(self, value: int) -> Bar: ...
    def label(self, label: Any) -> Bar: ...
    def text_value(self, value: str) -> Bar: ...
    def style(self, style: Style) -> Bar: ...
    def value_style(self, style: Style) -> Bar: ...

class BarGroup:
    """Group of bars in a bar chart.

    Maps to :class:`ratatui::widgets::BarGroup`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/struct.BarGroup.html
    """

    @staticmethod
    def new(bars: Sequence[Bar]) -> BarGroup: ...

class BarChart:
    """Bar chart widget.

    Maps to :class:`ratatui::widgets::BarChart`.
    See https://docs.rs/ratatui/0.29.0/ratatui/widgets/struct.BarChart.html
    """

    @staticmethod
    def new(groups: Sequence[BarGroup]) -> BarChart: ...
    def block(self, block: Block) -> BarChart: ...
    def style(self, style: Style) -> BarChart: ...
    def bar_width(self, value: int) -> BarChart: ...
    def max(self, value: int) -> BarChart: ...
    def bar_gap(self, value: int) -> BarChart: ...
    def group_gap(self, value: int) -> BarChart: ...
    def bar_style(self, style: Style) -> BarChart: ...
    def value_style(self, style: Style) -> BarChart: ...
    def label_style(self, style: Style) -> BarChart: ...
    def direction(self, direction: Direction) -> BarChart: ...

class Buffer:
    """Off-screen render buffer.

    Maps to :class:`ratatui::buffer::Buffer`.
    See https://docs.rs/ratatui/0.29.0/ratatui/buffer/struct.Buffer.html
    """

    @staticmethod
    def empty(area: Rect) -> Buffer: ...
    @property
    def area(self) -> Rect: ...
    def render_widget(self, widget: Any, area: Rect) -> None: ...
    def render_stateful_widget(
        self, widget: Any, area: Rect, state: Any
    ) -> None: ...
    def cell_symbol(self, x: int, y: int) -> str: ...
    def cell_fg(self, x: int, y: int) -> Color: ...
    def cell_bg(self, x: int, y: int) -> Color: ...
    def cell_modifier(self, x: int, y: int) -> Modifier: ...
    def set_string(
        self, x: int, y: int, string: str, style: Style
    ) -> None: ...
    def to_string_lines(self) -> list[str]: ...
    def to_ansi_lines(self, clip_bottom: bool = False) -> list[str]: ...
    def __repr__(self) -> str: ...

def render_widget(widget: Any, area: Rect, buffer: Buffer) -> None:
    """Render a supported widget into a buffer region."""

def render_stateful_widget(
    widget: Any, area: Rect, state: Any, buffer: Buffer
) -> None:
    """Render a supported stateful widget into a buffer region."""

class Frame:
    """Per-frame render context.

    Valid only for the duration of a :meth:`Terminal.draw` callback.
    Not thread-safe (``unsendable``).

    Maps to :class:`ratatui::Frame`.
    See https://docs.rs/ratatui/0.29.0/ratatui/terminal/struct.Frame.html
    """

    def area(self) -> Rect: ...
    def render_widget(self, widget: Any, area: Rect) -> None: ...
    def render_stateful_widget(
        self, widget: Any, area: Rect, state: Any
    ) -> None: ...
    def set_cursor_position(self, position: Position) -> None: ...
    def hide_cursor(self) -> None: ...
    def process_effects(
        self, manager: EffectManager, duration_ms: int, area: Rect
    ) -> None: ...
    def count(self) -> int: ...

class KeyEventKind(IntEnum):
    """Key event phase.

    Maps to :class:`crossterm::event::KeyEventKind`.
    """

    Press = ...
    Repeat = ...
    Release = ...

class KeyModifiers:
    """Keyboard modifier flags.

    Maps to :class:`crossterm::event::KeyModifiers`.
    """

    bits: int

    def contains(self, other: KeyModifiers) -> bool: ...
    def control(self) -> bool: ...
    def shift(self) -> bool: ...
    def alt(self) -> bool: ...

class KeyCode(IntEnum):
    """Key code category.

    Maps to :class:`crossterm::event::KeyCode` (simplified).
    """

    Char = ...
    Enter = ...
    Esc = ...
    Backspace = ...
    Tab = ...
    BackTab = ...
    Up = ...
    Down = ...
    Left = ...
    Right = ...
    Home = ...
    End = ...
    PageUp = ...
    PageDown = ...
    Insert = ...
    Delete = ...
    F = ...
    Null = ...
    Other = ...

class MouseEvent:
    """Mouse event data.

    Maps to :class:`crossterm::event::MouseEvent`.
    """

    kind: str
    x: int
    y: int
    button: str

class KeyEvent:
    """Keyboard event data.

    Maps to :class:`crossterm::event::KeyEvent`.
    """

    kind: KeyEventKind
    modifiers: KeyModifiers
    code_name: KeyCode

    def is_char(self, ch: str) -> bool: ...
    def char(self) -> Optional[str]: ...
    def is_up(self) -> bool: ...
    def is_down(self) -> bool: ...
    def is_left(self) -> bool: ...
    def is_right(self) -> bool: ...
    def is_enter(self) -> bool: ...
    def is_esc(self) -> bool: ...
    def is_backspace(self) -> bool: ...
    def is_tab(self) -> bool: ...
    def is_page_up(self) -> bool: ...
    def is_page_down(self) -> bool: ...
    def __repr__(self) -> str: ...

class Event:
    """Terminal input event."""

    kind: str
    key: Optional[KeyEvent]
    width: Optional[int]
    height: Optional[int]
    paste: Optional[str]
    mouse: Optional[MouseEvent]

class Terminal:
    """Ratatui terminal handle.

    Not thread-safe (``unsendable``).

    Maps to :class:`ratatui::DefaultTerminal`.
    See https://docs.rs/ratatui/0.29.0/ratatui/struct.DefaultTerminal.html
    """

    @staticmethod
    def init() -> Terminal: ...
    def draw(self, callback: Callable[[Frame], Any]) -> None: ...
    def clear(self) -> None: ...
    def size(self) -> Size: ...
    def __enter__(self) -> Terminal: ...
    def __exit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc_value: Optional[BaseException],
        traceback: Any,
    ) -> None: ...

def restore_terminal() -> None:
    """Restore the terminal to its pre-ratatui state."""

def poll_event(timeout_ms: int) -> Optional[Event]:
    """Poll for a terminal event with a timeout in milliseconds."""

def read_event() -> Event:
    """Block until a terminal event is available."""

class Motion(IntEnum):
    """Effect motion direction.

    Maps to :class:`tachyonfx::Motion`.
    See https://docs.rs/tachyonfx/0.25.0/tachyonfx/enum.Motion.html
    """

    UpToDown = ...
    DownToUp = ...
    LeftToRight = ...
    RightToLeft = ...

class Interpolation(IntEnum):
    """Effect interpolation curve.

    Maps to :class:`tachyonfx::Interpolation`.
    See https://docs.rs/tachyonfx/0.25.0/tachyonfx/enum.Interpolation.html
    """

    BackIn = ...
    BackOut = ...
    BackInOut = ...
    BounceIn = ...
    BounceOut = ...
    BounceInOut = ...
    CircIn = ...
    CircOut = ...
    CircInOut = ...
    CubicIn = ...
    CubicOut = ...
    CubicInOut = ...
    ElasticIn = ...
    ElasticOut = ...
    ElasticInOut = ...
    ExpoIn = ...
    ExpoOut = ...
    ExpoInOut = ...
    Linear = ...
    QuadIn = ...
    QuadOut = ...
    QuadInOut = ...
    QuartIn = ...
    QuartOut = ...
    QuartInOut = ...
    QuintIn = ...
    QuintOut = ...
    QuintInOut = ...
    Reverse = ...
    SmoothStep = ...
    Spring = ...
    SineIn = ...
    SineOut = ...
    SineInOut = ...

class ColorSpace(IntEnum):
    """Color interpolation space.

    Maps to :class:`tachyonfx::ColorSpace`.
    See https://docs.rs/tachyonfx/0.25.0/tachyonfx/enum.ColorSpace.html
    """

    Rgb = ...
    Hsl = ...
    Hsv = ...

class CellFilter:
    """Cell selection filter for effects.

    Not thread-safe (``unsendable``).

    Maps to :class:`tachyonfx::CellFilter`.
    See https://docs.rs/tachyonfx/0.25.0/tachyonfx/struct.CellFilter.html
    """

    ALL: CellFilter
    TEXT: CellFilter
    NON_EMPTY: CellFilter

    @staticmethod
    def fg_color(color: Color) -> CellFilter: ...
    @staticmethod
    def bg_color(color: Color) -> CellFilter: ...
    @staticmethod
    def inner(margin: Margin) -> CellFilter: ...
    @staticmethod
    def outer(margin: Margin) -> CellFilter: ...
    @staticmethod
    def area(rect: Rect) -> CellFilter: ...
    @staticmethod
    def all_of(filters: Sequence[CellFilter]) -> CellFilter: ...
    @staticmethod
    def any_of(filters: Sequence[CellFilter]) -> CellFilter: ...
    @staticmethod
    def not_(filter: CellFilter) -> CellFilter: ...

class Effect:
    """Terminal visual effect.

    Not thread-safe (``unsendable``).

    Maps to :class:`tachyonfx::Effect`.
    See https://docs.rs/tachyonfx/0.25.0/tachyonfx/struct.Effect.html
    """

    def with_area(self, area: Rect) -> Effect: ...
    def with_filter(self, filter: CellFilter) -> Effect: ...
    def with_color_space(self, color_space: ColorSpace) -> Effect: ...
    def with_rng(self, seed: int) -> Effect: ...
    def reversed(self) -> Effect: ...
    def name(self) -> str: ...
    def is_done(self) -> bool: ...
    def is_running(self) -> bool: ...
    def reset(self) -> None: ...

class EffectManager:
    """Effect scheduler and processor.

    Not thread-safe (``unsendable``).

    Maps to :class:`tachyonfx::EffectManager`.
    See https://docs.rs/tachyonfx/0.25.0/tachyonfx/struct.EffectManager.html
    """

    def __init__(self) -> None: ...
    def add(self, effect: Effect) -> None: ...
    def add_unique(self, key: str, effect: Effect) -> None: ...
    def unique(self, key: str, effect: Effect) -> Effect: ...
    def cancel(self, key: str) -> None: ...
    def is_running(self) -> bool: ...
    def process(
        self, duration_ms: int, buffer: Buffer, area: Rect
    ) -> None: ...

def fade_to_fg(
    color: Color,
    duration_ms: int,
    interpolation: Optional[Interpolation] = None,
) -> Effect:
    """Fade foreground to a color. See :func:`tachyonfx::fx::fade_to_fg`."""

def fade_from_fg(
    color: Color,
    duration_ms: int,
    interpolation: Optional[Interpolation] = None,
) -> Effect:
    """Fade foreground from a color. See :func:`tachyonfx::fx::fade_from_fg`."""

def fade_to(
    fg: Color,
    bg: Color,
    duration_ms: int,
    interpolation: Optional[Interpolation] = None,
) -> Effect:
    """Fade to foreground and background colors. See :func:`tachyonfx::fx::fade_to`."""

def fade_from(
    fg: Color,
    bg: Color,
    duration_ms: int,
    interpolation: Optional[Interpolation] = None,
) -> Effect:
    """Fade from foreground and background colors. See :func:`tachyonfx::fx::fade_from`."""

def paint(
    fg: Color,
    bg: Color,
    duration_ms: int,
    interpolation: Optional[Interpolation] = None,
) -> Effect:
    """Paint cells to colors. See :func:`tachyonfx::fx::paint`."""

def paint_fg(
    fg: Color,
    duration_ms: int,
    interpolation: Optional[Interpolation] = None,
) -> Effect:
    """Paint foreground color. See :func:`tachyonfx::fx::paint_fg`."""

def paint_bg(
    bg: Color,
    duration_ms: int,
    interpolation: Optional[Interpolation] = None,
) -> Effect:
    """Paint background color. See :func:`tachyonfx::fx::paint_bg`."""

def slide_in(
    direction: Motion,
    gradient_length: int,
    randomness: int,
    color: Color,
    duration_ms: int,
    interpolation: Optional[Interpolation] = None,
) -> Effect:
    """Slide effect in. See :func:`tachyonfx::fx::slide_in`."""

def slide_out(
    direction: Motion,
    gradient_length: int,
    randomness: int,
    color: Color,
    duration_ms: int,
    interpolation: Optional[Interpolation] = None,
) -> Effect:
    """Slide effect out. See :func:`tachyonfx::fx::slide_out`."""

def sweep_in(
    direction: Motion,
    gradient_length: int,
    randomness: int,
    color: Color,
    duration_ms: int,
    interpolation: Optional[Interpolation] = None,
) -> Effect:
    """Sweep effect in. See :func:`tachyonfx::fx::sweep_in`."""

def sweep_out(
    direction: Motion,
    gradient_length: int,
    randomness: int,
    color: Color,
    duration_ms: int,
    interpolation: Optional[Interpolation] = None,
) -> Effect:
    """Sweep effect out. See :func:`tachyonfx::fx::sweep_out`."""

def dissolve(
    duration_ms: int,
    interpolation: Optional[Interpolation] = None,
) -> Effect:
    """Dissolve effect. See :func:`tachyonfx::fx::dissolve`."""

def dissolve_to(
    style: Style,
    duration_ms: int,
    interpolation: Optional[Interpolation] = None,
) -> Effect:
    """Dissolve to a style. See :func:`tachyonfx::fx::dissolve_to`."""

def coalesce(
    duration_ms: int,
    interpolation: Optional[Interpolation] = None,
) -> Effect:
    """Coalesce effect. See :func:`tachyonfx::fx::coalesce`."""

def coalesce_from(
    style: Style,
    duration_ms: int,
    interpolation: Optional[Interpolation] = None,
) -> Effect:
    """Coalesce from a style. See :func:`tachyonfx::fx::coalesce_from`."""

def sleep_effect(duration_ms: int) -> Effect:
    """No-op delay effect. See :func:`tachyonfx::fx::sleep`."""

def sequence_effects(effects: Sequence[Effect]) -> Effect:
    """Run effects in sequence. See :func:`tachyonfx::fx::sequence`."""

def parallel_effects(effects: Sequence[Effect]) -> Effect:
    """Run effects in parallel. See :func:`tachyonfx::fx::parallel`."""

def repeating_effect(effect: Effect) -> Effect:
    """Repeat an effect forever. See :func:`tachyonfx::fx::repeating`."""

def ping_pong_effect(effect: Effect) -> Effect:
    """Ping-pong an effect. See :func:`tachyonfx::fx::ping_pong`."""

@overload
def repeat_effect(effect: Effect, *, times: int) -> Effect: ...
@overload
def repeat_effect(effect: Effect, *, duration_ms: int) -> Effect: ...
@overload
def repeat_effect(effect: Effect) -> Effect: ...
def repeat_effect(
    effect: Effect,
    times: Optional[int] = None,
    duration_ms: Optional[int] = None,
) -> Effect:
    """Repeat an effect. See :func:`tachyonfx::fx::repeat`."""

def delay_effect(duration_ms: int, effect: Effect) -> Effect:
    """Delay before starting an effect. See :func:`tachyonfx::fx::delay`."""

def prolong_start_effect(duration_ms: int, effect: Effect) -> Effect:
    """Hold the start state. See :func:`tachyonfx::fx::prolong_start`."""

def prolong_end_effect(duration_ms: int, effect: Effect) -> Effect:
    """Hold the end state. See :func:`tachyonfx::fx::prolong_end`."""

def saturate(
    duration_ms: int,
    fg: Optional[float] = None,
    bg: Optional[float] = None,
    interpolation: Optional[Interpolation] = None,
) -> Effect:
    """Adjust saturation. See :func:`tachyonfx::fx::saturate`."""

def saturate_fg(
    fg: float,
    duration_ms: int,
    interpolation: Optional[Interpolation] = None,
) -> Effect:
    """Adjust foreground saturation. See :func:`tachyonfx::fx::saturate_fg`."""

def lighten(
    duration_ms: int,
    fg: Optional[float] = None,
    bg: Optional[float] = None,
    interpolation: Optional[Interpolation] = None,
) -> Effect:
    """Lighten colors. See :func:`tachyonfx::fx::lighten`."""

def lighten_fg(
    fg: float,
    duration_ms: int,
    interpolation: Optional[Interpolation] = None,
) -> Effect:
    """Lighten foreground. See :func:`tachyonfx::fx::lighten_fg`."""

def darken(
    duration_ms: int,
    fg: Optional[float] = None,
    bg: Optional[float] = None,
    interpolation: Optional[Interpolation] = None,
) -> Effect:
    """Darken colors. See :func:`tachyonfx::fx::darken`."""

def darken_fg(
    fg: float,
    duration_ms: int,
    interpolation: Optional[Interpolation] = None,
) -> Effect:
    """Darken foreground. See :func:`tachyonfx::fx::darken_fg`."""

def hsl_shift(
    duration_ms: int,
    fg_h: Optional[float] = None,
    fg_s: Optional[float] = None,
    fg_l: Optional[float] = None,
    bg_h: Optional[float] = None,
    bg_s: Optional[float] = None,
    bg_l: Optional[float] = None,
    interpolation: Optional[Interpolation] = None,
) -> Effect:
    """Shift HSL values. See :func:`tachyonfx::fx::hsl_shift`."""

def hsl_shift_fg(
    h: float,
    s: float,
    l: float,
    duration_ms: int,
    interpolation: Optional[Interpolation] = None,
) -> Effect:
    """Shift foreground HSL. See :func:`tachyonfx::fx::hsl_shift_fg`."""

__all__ = (
    "Alignment",
    "Bar",
    "BarChart",
    "BarGroup",
    "Block",
    "BorderType",
    "Borders",
    "Buffer",
    "Cell",
    "CellFilter",
    "Clear",
    "Color",
    "ColorSpace",
    "Constraint",
    "Direction",
    "coalesce",
    "coalesce_from",
    "color_from_hex",
    "color_from_hsl",
    "color_lerp",
    "darken",
    "darken_fg",
    "delay_effect",
    "dissolve",
    "dissolve_to",
    "Effect",
    "EffectManager",
    "Event",
    "fade_from",
    "fade_from_fg",
    "fade_to",
    "fade_to_fg",
    "Flex",
    "Frame",
    "Gauge",
    "HighlightSpacing",
    "hsl_shift",
    "hsl_shift_fg",
    "Interpolation",
    "KeyCode",
    "KeyEvent",
    "KeyEventKind",
    "KeyModifiers",
    "Layout",
    "lighten",
    "lighten_fg",
    "Line",
    "LineGauge",
    "ListDirection",
    "ListItem",
    "ListState",
    "Margin",
    "MouseEvent",
    "Motion",
    "Modifier",
    "Offset",
    "Padding",
    "paint",
    "paint_bg",
    "paint_fg",
    "Paragraph",
    "parallel_effects",
    "ping_pong_effect",
    "poll_event",
    "Position",
    "prolong_end_effect",
    "prolong_start_effect",
    "RatList",
    "RatTable",
    "read_event",
    "Rect",
    "render_stateful_widget",
    "render_widget",
    "repeat_effect",
    "repeating_effect",
    "restore_terminal",
    "Row",
    "saturate",
    "saturate_fg",
    "ScrollDirection",
    "Scrollbar",
    "ScrollbarOrientation",
    "ScrollbarState",
    "sequence_effects",
    "Size",
    "sleep_effect",
    "slide_in",
    "slide_out",
    "Span",
    "Sparkline",
    "Style",
    "styled_span",
    "sweep_in",
    "sweep_out",
    "TableState",
    "Tabs",
    "tailwind_color",
    "Terminal",
    "Text",
    "TitlePosition",
    "Wrap",
)
