[project]
name = "xnano"
version = "0.0.52"
description = "build extremely 'nano' llm workflows"
readme = "readme.md"

requires-python = ">=3.9"

dependencies = [

]

[project.scripts] 
xnano = "xnano._cli:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mkdocs-material>=9.5.44",
    "mkdocs-material-extensions>=1.3.1",
    "mkdocstrings[python]>=0.27.0",
    "ruff>=0.7.3",
    "uv>=0.5.1",
    "mkdocs-jupyter>=0.25.1",
    "twine>=5.1.1",
    "pytest>=7.4.3",
]


[tool.hatch.build]
exclude = ["docs/"]
