"""xnano_core.rust.engine"""

from __future__ import annotations

from collections.abc import Callable, Sequence
from typing import Any, Optional

from xnano_core.rust.native import (
    Buffer,
    ClearType,
    CompletedFrame,
    Constraint,
    CursorStyle,
    Direction,
    Effect,
    KeyboardEnhancementFlags,
    KeyEvent,
    Margin,
    MouseEvent,
    Position,
    Rect,
    Size,
)

DrawableCallback = Callable[[Buffer, Rect], None]
"""Signature for :meth:`RenderContent.drawable` callbacks."""


class TerminalEventKind:
    Key: TerminalEventKind
    Resize: TerminalEventKind
    Paste: TerminalEventKind
    Mouse: TerminalEventKind
    FocusGained: TerminalEventKind
    FocusLost: TerminalEventKind
    Tick: TerminalEventKind


class TickEvent:
    elapsed_ms: int


class Event:
    kind: TerminalEventKind
    key: Optional[KeyEvent]
    width: Optional[int]
    height: Optional[int]
    paste: Optional[str]
    mouse: Optional[MouseEvent]
    tick: Optional[TickEvent]


class RenderContent:
    @staticmethod
    def empty() -> RenderContent: ...
    @staticmethod
    def widget(widget: Any) -> RenderContent: ...
    @staticmethod
    def stateful(widget: Any, state: Any) -> RenderContent: ...
    @staticmethod
    def drawable(callback: DrawableCallback) -> RenderContent: ...
    def is_empty(self) -> bool: ...
    def is_stateful(self) -> bool: ...
    def is_drawable(self) -> bool: ...


class RenderNode:
    def __init__(
        self,
        *,
        x: Optional[int] = None,
        y: Optional[int] = None,
        width: Optional[int] = None,
        height: Optional[int] = None,
        direction: Optional[Direction] = None,
        gap: int = 0,
        constraints: Optional[Sequence[Constraint]] = None,
        margin: Optional[Margin] = None,
        content: Optional[RenderContent] = None,
        cursor_hint: Optional[tuple[int, int]] = None,
        effect_key: Optional[str] = None,
        children: Optional[Sequence[RenderNode]] = None,
    ) -> None: ...
    @staticmethod
    def leaf(content: RenderContent) -> RenderNode: ...
    @staticmethod
    def row(
        children: Sequence[RenderNode],
        *,
        constraints: Optional[Sequence[Constraint]] = None,
        gap: int = 0,
        margin: Optional[Margin] = None,
    ) -> RenderNode: ...
    @staticmethod
    def column(
        children: Sequence[RenderNode],
        *,
        constraints: Optional[Sequence[Constraint]] = None,
        gap: int = 0,
        margin: Optional[Margin] = None,
    ) -> RenderNode: ...
    @staticmethod
    def stack(
        x: int,
        y: int,
        width: int,
        height: int,
        children: Sequence[RenderNode],
    ) -> RenderNode: ...
    def get_children(self) -> list[RenderNode]: ...
    def get_content(self) -> RenderContent: ...
    def get_effect_key(self) -> Optional[str]: ...
    def has_absolute_geometry(self) -> bool: ...


class TerminalRef:
    def draw(self, callback: Callable[[Any], Any]) -> None: ...
    def try_draw(self, callback: Callable[[Any], Any]) -> CompletedFrame: ...
    def flush(self) -> None: ...
    def clear(self) -> None: ...
    def size(self) -> Size: ...


class Session:
    @staticmethod
    def init(*, tick_rate_ms: Optional[int] = None) -> Session: ...
    @staticmethod
    def offscreen(width: int, height: int) -> Session: ...
    def render(self, node: RenderNode) -> None: ...
    def poll_event(self, timeout_ms: int = 16) -> Optional[Event]: ...
    def read_event(self) -> Event: ...
    def buffer_snapshot(self) -> Buffer: ...
    def add_effect(self, effect: Effect) -> None: ...
    def add_unique_effect(self, key: str, effect: Effect) -> None: ...
    def cancel_effect(self, key: str) -> None: ...
    def is_animating(self) -> bool: ...
    def effect_area_for(self, key: str) -> Optional[Rect]: ...
    def get_terminal(self) -> TerminalRef: ...
    def enable_raw_mode(self) -> None: ...
    def disable_raw_mode(self) -> None: ...
    def enable_mouse_capture(self) -> None: ...
    def disable_mouse_capture(self) -> None: ...
    def enable_bracketed_paste(self) -> None: ...
    def disable_bracketed_paste(self) -> None: ...
    def enable_focus_change(self) -> None: ...
    def disable_focus_change(self) -> None: ...
    def enter_alternate_screen(self) -> None: ...
    def leave_alternate_screen(self) -> None: ...
    def push_keyboard_enhancement_flags(self, flags: KeyboardEnhancementFlags) -> None: ...
    def pop_keyboard_enhancement_flags(self) -> None: ...
    def show_cursor(self) -> None: ...
    def hide_cursor(self) -> None: ...
    def set_cursor_style(self, style: CursorStyle) -> None: ...
    def get_cursor_style(self) -> CursorStyle: ...
    def move_cursor_to(self, x: int, y: int) -> None: ...
    def save_cursor_position(self) -> None: ...
    def restore_cursor_position(self) -> None: ...
    def get_cursor_position(self) -> Position: ...
    def get_size(self) -> Size: ...
    def get_window_size(self) -> Size: ...
    def get_last_frame_area(self) -> Optional[Rect]: ...
    def is_raw_mode_enabled(self) -> bool: ...
    def is_mouse_capture_enabled(self) -> bool: ...
    def is_bracketed_paste_enabled(self) -> bool: ...
    def is_focus_change_enabled(self) -> bool: ...
    def is_alternate_screen_enabled(self) -> bool: ...
    def is_cursor_visible(self) -> bool: ...
    def clear(self, clear_type: ClearType) -> None: ...
    def set_title(self, title: str) -> None: ...
    def get_title(self) -> Optional[str]: ...
    def scroll_up(self, count: int = 1) -> None: ...
    def scroll_down(self, count: int = 1) -> None: ...
    def begin_synchronized_update(self) -> None: ...
    def end_synchronized_update(self) -> None: ...
    def restore(self) -> None: ...
    def __enter__(self) -> Session: ...
    def __exit__(
        self,
        exc_type: object,
        exc_value: object,
        traceback: object,
    ) -> bool: ...